version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosec
    - bodyclose
    - revive
    - gocritic
    - misspell

  settings:
    gosec:
      excludes:
        - G401
        - G704
    revive:
      rules:
        - name: exported
          disabled: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports